// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr3DOcn6bND0csWvfTD9IEnnicP-Jayh4',
    appId: '1:954078368857:web:d1397e0db5bb4f6c750d48',
    messagingSenderId: '954078368857',
    projectId: 'themusicstore-5c9e1',
    authDomain: 'themusicstore-5c9e1.firebaseapp.com',
    storageBucket: 'themusicstore-5c9e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG5d6wHt9Pz0ZUIQsMPFrwPdJeqN1YqeI',
    appId: '1:954078368857:android:b09b1d224cd4d03d750d48',
    messagingSenderId: '954078368857',
    projectId: 'themusicstore-5c9e1',
    storageBucket: 'themusicstore-5c9e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzj2dBlf1kafqOlnNieM5-qpDXPuszxi8',
    appId: '1:954078368857:ios:ca750df6f7d03f77750d48',
    messagingSenderId: '954078368857',
    projectId: 'themusicstore-5c9e1',
    storageBucket: 'themusicstore-5c9e1.appspot.com',
    iosClientId: '954078368857-dp1pjq7klk5hgk2cfe4rgls2vbhirhq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzj2dBlf1kafqOlnNieM5-qpDXPuszxi8',
    appId: '1:954078368857:ios:ca750df6f7d03f77750d48',
    messagingSenderId: '954078368857',
    projectId: 'themusicstore-5c9e1',
    storageBucket: 'themusicstore-5c9e1.appspot.com',
    iosClientId: '954078368857-dp1pjq7klk5hgk2cfe4rgls2vbhirhq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
